### ISSUE TITLE
How to generate the same shared secret through different keypairs?

### ISSUE THREAD

**Issue by Chewhern** [ektrah/nsec#46] opened 2020-10-01 11:26 UTC
I was wondering if there was any way to generate the same shared secret through different keypairs because the following code that I write when I compare it to other shared secret as shown in the code below always giving the output of "false" or do I not need to do the equal comparison in the first place as the shared secret will always be working and the same?

            var algorithm = KeyAgreementAlgorithm.X25519;
            var creationParameters = new KeyCreationParameters
            {
                ExportPolicy = KeyExportPolicies.AllowPlaintextExport
            };
            var key = Key.Create(algorithm,creationParameters);
            var key2 = Key.Create(algorithm,creationParameters);
            var client_key_1 = key;
            var client_Pkey_1 = PublicKey.Import(algorithm, key2.Export(KeyBlobFormat.NSecPublicKey),KeyBlobFormat.NSecPublicKey);
            var client_key_2 = key;
            var client_Pkey_2 = PublicKey.Import(algorithm, key.Export(KeyBlobFormat.NSecPublicKey), KeyBlobFormat.NSecPublicKey);
            var sharedsecret = KeyAgreementAlgorithm.X25519.Agree(client_key_1,client_Pkey_1);
            var sharedsecret2 = KeyAgreementAlgorithm.X25519.Agree(client_key_2, client_Pkey_2);
            Console.WriteLine(sharedsecret.Equals(sharedsecret2));

Any help will be appreciated and can I do signing with KeyAgreementAlgorithm?

**Comment by sigaloid** [comment] 2020-10-02 13:25
Don't import public keys, just do key.PublicKey or key2.PublicKey.

**Comment by Chewhern** [comment] 2020-10-02 17:03
> No; see https://nsec.rocks/docs/api/nsec.cryptography.signaturealgorithm

I tried with this again but the shared secret when i compare them again it's still not the same and gives me "false" as output

            var algorithm = KeyAgreementAlgorithm.X25519;
            var creationParameters = new KeyCreationParameters
            {
                ExportPolicy = KeyExportPolicies.AllowPlaintextExport
            };
            var key = Key.Create(algorithm, creationParameters);
            var key2 = Key.Create(algorithm, creationParameters);
            var sharedsecret = KeyAgreementAlgorithm.X25519.Agree(key, key2.PublicKey);
            var sharedsecret2 = KeyAgreementAlgorithm.X25519.Agree(key2, key.PublicKey);
            Console.WriteLine(sharedsecret.Equals(sharedsecret2));

Any ideas?

**Comment by sigaloid** [comment] 2020-10-02 23:51
You can't directly compare sharedsecrets IIRC. 

Use a KDF (this is what you would use because you cannot just directly encrypt with a shared secret): https://github.com/sigaloid/cage/blob/master/cage/Program.cs#L286

That is a really messed up function I linked, and it's horrible code practice to have one long line of code, but it shows how you would do it; here's a better structure.

```
var sharedsecret1 = KeyAgreementAlgorithm.X25519.Agree(key1, key2.publickey);
var sharedsecret2 = KeyAgreementAlgorithm.X25519.Agree(key2, key1.publickey);
var derivedkey1 = KeyDerivationAlgorithm.HkdfSha512.DeriveKey(sharedsecret1, ReadOnlySpan<byte>.Empty, ReadOnlySpan<byte>.Empty, AeadAlgorithm.ChaCha20Poly1305, new KeyCreationParameters {ExportPolicy = KeyExportPolicies.AllowPlaintextArchiving});
var derivedkey2 = KeyDerivationAlgorithm.HkdfSha512.DeriveKey(sharedsecret2, ReadOnlySpan<byte>.Empty, ReadOnlySpan<byte>.Empty, AeadAlgorithm.ChaCha20Poly1305, new KeyCreationParameters {ExportPolicy = KeyExportPolicies.AllowPlaintextArchiving});
bool isEqual = derivedkey1.Equals(derivedkey2);
Console.WriteLine(isEqual);
```


This is an example I wrote in notepad, but that's the general structure.

**Comment by Chewhern** [comment] 2020-10-03 09:28
> You can't directly compare sharedsecrets IIRC.
> 
> Use a KDF (this is what you would use because you cannot just directly encrypt with a shared secret): https://github.com/sigaloid/cage/blob/master/cage/Program.cs#L286
> 
> That is a really messed up function I linked, and it's horrible code practice to have one long line of code, but it shows how you would do it; here's a better structure.
> 
> ```
> var sharedsecret1 = KeyAgreementAlgorithm.X25519.Agree(key1, key2.publickey);
> var sharedsecret2 = KeyAgreementAlgorithm.X25519.Agree(key2, key1.publickey);
> var derivedkey1 = KeyDerivationAlgorithm.HkdfSha512.DeriveKey(sharedsecret1, ReadOnlySpan<byte>.Empty, ReadOnlySpan<byte>.Empty, AeadAlgorithm.ChaCha20Poly1305, new KeyCreationParameters {ExportPolicy = KeyExportPolicies.AllowPlaintextArchiving});
> var derivedkey2 = KeyDerivationAlgorithm.HkdfSha512.DeriveKey(sharedsecret2, ReadOnlySpan<byte>.Empty, ReadOnlySpan<byte>.Empty, AeadAlgorithm.ChaCha20Poly1305, new KeyCreationParameters {ExportPolicy = KeyExportPolicies.AllowPlaintextArchiving});
> bool isEqual = derivedkey1.Equals(derivedkey2);
> Console.WriteLine(isEqual);
> ```
> 
> This is an example I wrote in notepad, but that's the general structure. In practice you would set a few fields I left as ReadOnlySpan.Empty for security (like salt for the KDF) and maybe use HkdfSha256 for some reason. But it's the same idea.
> 
> A sharedsecret is just that; a shared secret. it must be converted to a key before it can be used. (and once you do, export it as NSec.SymmetricKey if you need to)

I tried your code but it still gives me false..

**Comment by sigaloid** [comment] 2020-10-03 16:32
My apologies. The issue is with the .equals(), you cannot compare these objects like that (nor, apparently, byte arrays). I should have tested it beforehand. Here:

```
            var algorithm = KeyAgreementAlgorithm.X25519;
            var creationParameters = new KeyCreationParameters
            {
                ExportPolicy = KeyExportPolicies.AllowPlaintextExport
            };
            var key = Key.Create(algorithm, creationParameters);
            var key2 = Key.Create(algorithm, creationParameters);
            var sharedsecret1 = KeyAgreementAlgorithm.X25519.Agree(key, key2.PublicKey);
            var sharedsecret2 = KeyAgreementAlgorithm.X25519.Agree(key2, key.PublicKey);
            var derivedkey1 = KeyDerivationAlgorithm.HkdfSha512.DeriveKey(sharedsecret1, ReadOnlySpan<byte>.Empty, ReadOnlySpan<byte>.Empty, AeadAlgorithm.ChaCha20Poly1305, creationParameters);
            var derivedkey2 = KeyDerivationAlgorithm.HkdfSha512.DeriveKey(sharedsecret2, ReadOnlySpan<byte>.Empty, ReadOnlySpan<byte>.Empty, AeadAlgorithm.ChaCha20Poly1305, creationParameters);
            var derivedkey1bytes = Convert.ToBase64String(derivedkey1.Export(KeyBlobFormat.NSecSymmetricKey));
            var derivedkey2bytes = Convert.ToBase64String(derivedkey2.Export(KeyBlobFormat.NSecSymmetricKey));
            
            Console.WriteLine(derivedkey1bytes==derivedkey2bytes);
```

This directly compares the base64 representation of the shared key. It outputs "True" for me. Here's the entire flow: 

1. Calculate SharedSecret from X25519 keys with KeyAgreementAlgorithm
2. convert it to keys with KeyDerivationAlgorithm
3. export the keys and convert it to base64. 
4. compare the base64 strings

If you have any trouble with this, please let me know.

**Comment by ektrah** [comment] 2020-10-17 11:16
Just to confirm: The SharedSecret.Equals method doesn't compare the objects for having the same value, just for being the same object. Passing the SharedSecret objects through a KeyDerivationAlgorithm should lead to the same result.

(Closing this issue since the question seems to be answered.)

**Closed by ektrah** 2020-10-17 11:16 UTC
